name: drop_check
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  google_nav_bar: ^5.0.6
  shared_preferences_android: ^2.2.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  firebase_database: ^10.4.9
  cloud_firestore: ^4.15.8
  url_launcher: ^6.3.0
  firebase_messaging: ^14.7.19
  firebase_analytics: ^10.8.9
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  meta: ^1.10.0
  flutter_launcher_icons: ^0.13.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  get_it: ^7.6.7
  injectable: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  injectable_generator: ^2.4.2
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"



flutter:


  uses-material-design: true

  
  assets:
    - lib/images/